baseurl = "https://bengin.netlify.app"
languageCode = "en-us"
title = "Ben Gin's Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"
    note = "/note/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
#[[menu.main]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 4
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; Ben Gin, 2020 . Powered by the [xmin theme](https://github.com/yihui/hugo-xmin) for [Hugo](https://gohugo.io)"
#    footer = "&copy; [Yihui Xie](https://yihui.name) 2017 -- 2019 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"
